services:
  dashboard-api:
    image: hub.opensciencegrid.org/mwestphall/personal-ap-dashboard-api:latest
    build:
      context: dashboard-api
  dashboard-ui:
    image: hub.opensciencegrid.org/mwestphall/personal-ap-dashboard-ui:latest
    build:
      context: dashboard-ui
