resolver kube-dns.kube-system.svc.cluster.local valid=30s;

server {
    listen       80;

    location ~ ^/(.*)$ {
        proxy_pass_request_headers on;
        set $pesronal_ap dashboard-ui-service.default.svc.cluster.local:80;
        proxy_pass http://$pesronal_ap/$1;
    }
}
