resolver kube-dns.kube-system.svc.cluster.local valid=30s;

server {
    listen       80;

    location /api/ {
        proxy_pass_request_headers on;
        proxy_pass http://dashboard-api-service.default.svc.cluster.local:80/;
    }

    location / {
        proxy_pass http://dashboard-ui-service.default.svc.cluster.local:80;
    }

    location ~ ^/dashboards/([^/]*)/(.*)$ {
        set $netid $1;
        set $dashboard $2;
        proxy_pass http://$netid-self-service-ap.default.svc.cluster.local:8888/dashboards/$netid/$dashboard;
    }
}
