# resolver 10.0.0.1 ipv4=on valid=300s;

# oidc_provider my_idp {
#     issuer        "https://cilogon.org";
#     client_id     "cilogon:/client_id/534864d355885529ea6033daa9bdf0ec";
#     client_secret "H1JCZ3DLWGs6Mfs4z3b_pJ9AvinxP1-BTu_YSFpLkHkJU1N_lTqbVMFpFhzhajWETXDePgJNdYcMQ_LOh7F0Vg";
# }

# server {
#     location / {
#         auth_oidc my_idp;

#         proxy_set_header username $oidc_claim_sub;
#         proxy_pass       http://backend;
#     }
# }
