apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-ap
spec:
  template:
    spec:
      containers:
      - name: submit
        env:
        - name: _CONDOR_TCP_FORWARDING_HOST
          value: westphall-self-service-ap.default.svc.cluster.local
        - name: _CONDOR_SHARED_PORT_PORT
          value: '9619'
        - name: JUPYTERHUB_SERVICE_PREFIX
          value: /dashboards/westphall/
        - name: NETID
          value: westphall
        - name: JUPYTER_TOKEN
          value: ""
