# Reference to the baseline definition of the self-service AP
resources:
- ../base/self-service-ap/

# Prepend `$AP_USER_ID-` to the name of every created resource to distinguish them from other instances of the self-service AP in the same Namespace
namePrefix: "westphall-"

# Add the `$AP_NAME` label to each created resource. Required so that the AP's network configuration objects can direct TCP traffic to the appropriate instance of the self-service AP container
labels:
- pairs:
    app: westphall-self-service-ap
  includeSelectors: true

# Update the internal configuration of the AP with references to the selected External DNS name
# Set AP resource requests based on researcher requirements.
patches:
- path: deployment-patch.yaml
- target:
    version: v1
    kind: Service
    name: self-service-ap
  path: service-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: self-service-ap
  path: deployment-port-patch.yaml
