# Reference to the baseline definition of the  AP
resources:
- ../base/-ap/

# Prepend `$AP_USER_ID-` to the name of every created resource to distinguish them from other instances of the  AP in the same Namespace
namePrefix: "westphall-"

# Add the `$AP_NAME` label to each created resource. Required so that the AP's network configuration objects can direct TCP traffic to the appropriate instance of the  AP container
labels:
- pairs:
    app: westphall--ap
  includeSelectors: true

# Update the internal configuration of the AP with references to the selected External DNS name
# Set AP resource requests based on researcher requirements.
patches:
- path: deployment-patch.yaml
- target:
    version: v1
    kind: Service
    name: -ap
  path: service-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: -ap
  path: deployment-port-patch.yaml
